apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-pac-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineSpec:
    tasks:
      - name: echo-hello
        taskSpec:
          steps:
            - name: say-hi
              image: alpine
              script: |
                echo "👋 Hello from Pipelines as Code test!"
